# Generated by Django 4.2.11 on 2024-05-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("createDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventName", models.CharField(max_length=150)),
                ("max_limit", models.PositiveIntegerField()),
                ("createDate", models.DateTimeField(auto_now_add=True)),
                (
                    "createUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="createdEvents",
                        to="manage_system.user",
                    ),
                ),
                (
                    "joinedUsers",
                    models.ManyToManyField(
                        blank=True, related_name="joinedEvents", to="manage_system.user"
                    ),
                ),
            ],
            options={"ordering": ("-createDate",),},
        ),
    ]
