# Generated by Django 4.2.11 on 2024-06-01 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("manage_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="eventDateTime",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
