# Generated by Django 4.2.11 on 2024-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0002_event_eventdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draftId',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sheetId',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
