# Generated by Django 4.2.11 on 2024-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0003_event_draftid_event_sheetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_limit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
