# Generated by Django 4.2.11 on 2024-06-04 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manage_system", "0005_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="createUser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="createdEvents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
