# Generated by Django 4.2.11 on 2024-05-05 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("body", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ("-date",),},
        ),
    ]
